.PHONY: clean All

All:
	@echo "----------Building project:[ Section16_Polymorphism_project - Debug ]----------"
	@cd "Section16_Polymorphism_project" && "$(MAKE)" -f  "Section16_Polymorphism_project.mk"
clean:
	@echo "----------Cleaning project:[ Section16_Polymorphism_project - Debug ]----------"
	@cd "Section16_Polymorphism_project" && "$(MAKE)" -f  "Section16_Polymorphism_project.mk" clean
